version: '3'
services:
    db:
        image: "microsoft/mssql-server-linux:latest"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Password1!"
            ACCEPT_EULA: "Y"
        networks:
            - "mssql"
    glassfish:
        depends_on: 
            - "db"
        image: "fontys/kwetter:latest"
        ports:
            - "4848:4848"
            - "8080:8080"
        networks:
            - "mssql"

networks:
  mssql:
    driver: overlay
