version: '3'
services:
    db:
        image: "microsoft/mssql-server-linux:latest"
        environment:
            SA_PASSWORD: "Password1!"
            ACCEPT_EULA: "Y"
        networks:
            - "mssql"
    glassfish:
        depends_on: 
            - "db"
        image: "fontys/kwetter:latest"
        ports:
            - "0.0.0.0:443:4848"
            - "0.0.0.0:80:8080"
        networks:
            - "mssql"

networks:
  mssql:
    driver: overlay
